Repository honeycombio/honeymarker, pull requests merged in 2021-06, with the labels that each got.

#12 update maintainer contact email address
  Dockerfile
  build-pkg.sh
Labels: type: maintenance, version: no bump

#10 honeymarker: Move to go modules
  .circleci/config.yml
  Godeps/Godeps.json
  Godeps/Readme
  go.mod
  go.sum
  vendor/github.com/jessevdk/go-flags/.travis.yml
  vendor/github.com/jessevdk/go-flags/LICENSE
  vendor/github.com/jessevdk/go-flags/README.md
  vendor/github.com/jessevdk/go-flags/arg.go
  vendor/github.com/jessevdk/go-flags/check_crosscompile.sh
  vendor/github.com/jessevdk/go-flags/closest.go
  vendor/github.com/jessevdk/go-flags/command.go
  vendor/github.com/jessevdk/go-flags/completion.go
  vendor/github.com/jessevdk/go-flags/convert.go
  vendor/github.com/jessevdk/go-flags/error.go
  vendor/github.com/jessevdk/go-flags/flags.go
  vendor/github.com/jessevdk/go-flags/group.go
  vendor/github.com/jessevdk/go-flags/help.go
  vendor/github.com/jessevdk/go-flags/ini.go
  vendor/github.com/jessevdk/go-flags/man.go
  vendor/github.com/jessevdk/go-flags/multitag.go
  vendor/github.com/jessevdk/go-flags/option.go
  vendor/github.com/jessevdk/go-flags/optstyle_other.go
  vendor/github.com/jessevdk/go-flags/optstyle_windows.go
  vendor/github.com/jessevdk/go-flags/parser.go
  vendor/github.com/jessevdk/go-flags/termsize.go
  vendor/github.com/jessevdk/go-flags/termsize_nosysioctl.go
  vendor/github.com/jessevdk/go-flags/tiocgwinsz_bsdish.go
  vendor/github.com/jessevdk/go-flags/tiocgwinsz_linux.go
  vendor/github.com/jessevdk/go-flags/tiocgwinsz_other.go
Labels: type: maintenance, version: no bump

#14 update Go from 1.12 to 1.16; update orbs and cimgs
  .circleci/config.yml
Labels: status: review needed, version: bump patch

#11 honeymarker: Add hidden flag to set Authorization header
  add.go
  list.go
  main.go
  rm.go
  update.go
Labels: status: review needed
